### ISSUE TITLE
Is there any method to record SVO file without CUDA?

### ISSUE THREAD

**Issue by memoryunreal** [stereolabs/zed-open-capture#27]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

I want to record the SVO file using a mini PC without NVIDIA graphics, is there any method to use this SDK without CUDA?
And then I will use a Linux server with CUDA to export the SVO file in any format.

**Comment by Myzhar** [comment]
Hi @memoryunreal 
this is the ZED Open Capture repository and it is not related to the ZED SDK.
We cannot add SVO features here because this is an Open Source project and SVO handling is closed.

Please write an email to support@stereolabs.com or write a post on the [forum](https://community.stereolabs.com) for your request.
